/**
 * @kit/patterns-web —— 大端页面模板（只编排已登记组件，数据走 core hooks）
 * 规则：不沉淀通用能力；可复用内容回流到 ui-web。
 */
export * from './login-page/LoginPage'
export * from './list-page/ListPage'
export * from './detail-page/DetailPage'
export * from './form-page/FormPage'
export * from './dashboard-page/DashboardPage'
export * from './settings-page/SettingsPage'
export * from './profile-page/ProfilePage'
export * from './onboarding-page/OnboardingPage'
export * from './hero-page/HeroPage'
export * from './error-page/ErrorPage'
export * from './chat-page/ChatPage'
export * from './product-detail-page/ProductDetailPage'
export * from './workspace-page/WorkspacePage'
export * from './cart-page/CartPage'
export * from './theme-palette-page/ThemePalettePage'
export * from './glass-page/GlassPage'
export * from './material-elevation-page/MaterialElevationPage'
export * from './typography-page/TypographyPage'
export * from './dark-mode-showcase/DarkModeShowcase'
export * from './neumorphism-page/NeumorphismPage'
export * from './empty-state-showcase/EmptyStateShowcase'
export * from './icon-gallery/IconGallery'
export * from './steps-flow-page/StepsFlowPage'
export * from './notification-center-page/NotificationCenterPage'
export * from './login-register-page/LoginRegisterPage'
export * from './data-table-page/DataTablePage'
