/**
 * Style Dictionary v4 build config
 * One token source (DTCG JSON) -> three stack outputs:
 *   dist/web/tokens.light.css | tokens.dark.css    (CSS vars, :root / .dark)
 *   dist/mini/tokens.light.scss | tokens.dark.scss (SCSS vars, mini-program / H5)
 *   dist/mini/tokens.light.ts | tokens.dark.ts     (TS constants)
 *   dist/native/tamagui.light.ts | tamagui.dark.ts (Tamagui token fragments)
 *   dist/docs/tokens-table.md                     (token inventory for hub/docs)
 * Run: pnpm tokens:build | Watch: pnpm tokens:watch
 */
import StyleDictionary from 'style-dictionary'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const srcDir = join(here, 'src', 'tokens')
const distDir = join(here, 'dist')

const NON_COLOR_SOURCES = [
  'spacing.json',
  'radius.json',
  'typography.json',
  'shadow.json',
  'motion.json',
  'z-index.json',
  'breakpoint.json',
  'size.json',
].map((f) => join(srcDir, f))

const LIGHT_SOURCES = [
  join(srcDir, 'color-primitive.json'),
  join(srcDir, 'color-semantic-light.json'),
  ...NON_COLOR_SOURCES,
]
const DARK_SOURCES = [
  join(srcDir, 'color-primitive.json'),
  join(srcDir, 'color-semantic-dark.json'),
]

/** Dark theme exports semantic colors only; primitive palettes (gray/brand/...) are excluded. */
const semanticOnly = (token) =>
  !['gray', 'brand', 'success', 'warning', 'danger', 'info', 'white', 'black'].includes(
    token.path[0],
  )

const camelCase = (input) => input.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())

/** Group tokens by top-level category into a plain nested object (Tamagui-shaped). */
const groupByCategory = (dictionary) => {
  const group = {}
  for (const token of dictionary.allTokens) {
    const category = token.path[0]
    const key = camelCase(token.path.slice(1).join('-'))
    const value = token.$value ?? token.value
    ;(group[category] ??= {})[key] = value
  }
  return group
}

StyleDictionary.registerFormat({
  name: 'tamagui/tokens',
  format: ({ dictionary, options }) => {
    const group = groupByCategory(dictionary)
    return [
      '// AUTO-GENERATED by Style Dictionary. Do not edit. Source: packages/tokens/src',
      `// theme: ${options.theme}`,
      `export const ${options.theme}Tokens = ${JSON.stringify(group, null, 2)} as const`,
      '',
    ].join('\n')
  },
})

StyleDictionary.registerFormat({
  name: 'ts/nested-const',
  format: ({ dictionary, options }) => {
    const group = groupByCategory(dictionary)
    return [
      '// AUTO-GENERATED by Style Dictionary. Do not edit. Source: packages/tokens/src',
      `// theme: ${options.theme}`,
      `export const ${options.theme}Tokens = ${JSON.stringify(group, null, 2)} as const`,
      '',
    ].join('\n')
  },
})

/** Markdown token inventory (hub / docs). */
StyleDictionary.registerFormat({
  name: 'docs/markdown-table',
  format: ({ dictionary }) => {
    const groups = new Map()
    for (const token of dictionary.allTokens) {
      const category = token.path[0]
      if (!groups.has(category)) groups.set(category, [])
      groups.get(category).push(token)
    }
    const lines = ['# Design Tokens (auto-generated, do not edit)', '']
    for (const [category, tokens] of groups) {
      lines.push(`## ${category}`, '', '| Token | Value | Type |', '| --- | --- | --- |')
      for (const t of tokens) {
        lines.push(`| ${t.name} | ${String(t.$value ?? t.value)} | ${t.$type ?? t.type ?? ''} |`)
      }
      lines.push('')
    }
    return lines.join('\n')
  },
})

const cssTransforms = ['attribute/cti', 'name/kebab', 'time/seconds', 'size/px', 'color/css']

const basePlatforms = (theme) => {
  const isDark = theme === 'dark'
  // v4: file-level filter (platform-level filter is not invoked)
  const withFilter = (file) => (isDark ? { ...file, filter: semanticOnly } : file)
  return {
    [`web-${theme}`]: {
      transforms: cssTransforms,
      prefix: 'kit',
      files: [
        withFilter({
          destination: `web/tokens.${theme}.css`,
          format: 'css/variables',
          options: { selector: isDark ? '.dark' : ':root' },
        }),
      ],
    },
    [`mini-scss-${theme}`]: {
      transforms: cssTransforms,
      prefix: 'kit',
      files: [withFilter({ destination: `mini/tokens.${theme}.scss`, format: 'scss/variables' })],
    },
    [`mini-ts-${theme}`]: {
      transforms: ['attribute/cti', 'name/camel', 'size/px', 'color/css'],
      files: [
        withFilter({
          destination: `mini/tokens.${theme}.ts`,
          format: 'ts/nested-const',
          options: { theme },
        }),
      ],
    },
    [`native-${theme}`]: {
      transforms: ['attribute/cti', 'name/camel', 'size/px', 'color/css'],
      files: [
        withFilter({
          destination: `native/tamagui.${theme}.ts`,
          format: 'tamagui/tokens',
          options: { theme },
        }),
      ],
    },
  }
}

const makeConfig = (theme, sources) => {
  const platforms = {
    ...basePlatforms(theme),
    ...(theme === 'light'
      ? {
          'docs-table': {
            transforms: cssTransforms,
            files: [{ destination: 'docs/tokens-table.md', format: 'docs/markdown-table' }],
          },
        }
      : {}),
  }
  for (const p of Object.values(platforms)) p.buildPath = 'dist/'
  return { source: sources, preprocessors: ['tokens-stdion'], platforms }
}

const run = async () => {
  const themes = {
    light: new StyleDictionary(makeConfig('light', LIGHT_SOURCES)),
    dark: new StyleDictionary(makeConfig('dark', DARK_SOURCES)),
  }
  for (const [name, sd] of Object.entries(themes)) {
    await sd.buildAllPlatforms()
    console.log(`[tokens] ${name} theme built -> dist/`)
  }
  const expected = [
    'web/tokens.light.css',
    'web/tokens.dark.css',
    'mini/tokens.light.scss',
    'mini/tokens.dark.scss',
    'mini/tokens.light.ts',
    'mini/tokens.dark.ts',
    'native/tamagui.light.ts',
    'native/tamagui.dark.ts',
    'docs/tokens-table.md',
  ]
  const missing = expected.filter((f) => {
    try {
      readFileSync(join(distDir, f))
      return false
    } catch {
      return true
    }
  })
  if (missing.length) {
    console.error('[tokens] missing outputs:', missing.join(', '))
    process.exit(1)
  }
  console.log('[tokens] all outputs verified OK')
}

run().catch((err) => {
  console.error(err)
  process.exit(1)
})
